### ISSUE TITLE
[cert-manager] Automatic creation of target secrets

### ISSUE THREAD

**Issue by sc250024** [EmberStack/ES.Kubernetes.Reflector#8] opened 2019-07-04 12:02 UTC
Greetings,

I'm using the `cert-manager` extension based on the instructions here: https://github.com/EmberStack/ES.Kubernetes.Reflector#optional-cert-manager-extension.

However, I'm a bit confused: does the `reflector` automatically create the mirrored secrets in the other namespaces? Or are you supposed to create a 'dummy' secret in the other namespace with the correct annotation, and only then does `reflector` populate the contents with the source?

Basically, I get the following entries in the log files:
```
11:51:07.547 +00:00 [INF] (ES.Kubernetes.Reflector.Services.SecretsMirror) Starting
11:51:07.840 +00:00 [INF] (ES.Kubernetes.Reflector.Services.ConfigMapMirror) Starting
11:51:07.890 +00:00 [INF] (ES.Kubernetes.Reflector.Services.CertManagerMirror) Starting
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
11:51:08.550 +00:00 [INF] (ES.Kubernetes.Reflector.Services.CertManagerMirror) Certificates definition set to version v1alpha1
11:57:08.022 +00:00 [INF] (ES.Kubernetes.Reflector.Services.CertManagerMirror) Patching cert-manager/star-mycompany-io-tls to match certificate cert-manager/mycompany-io reflection annotations
11:57:08.077 +00:00 [INF] (ES.Kubernetes.Reflector.Services.CertManagerMirror) Patching cert-manager/star-mycompany-com-tls to match certificate cert-manager/mycompany-com reflection annotations
```

Which means that the source secrets are properly annotated. However, I don't see any new secrets being created in any of the other namespaces.

**Comment by winromulus** [comment] 2019-07-04 17:17
Hi @sc250024 

The cert-manager extension allows you to annotate the secret created by cert-manager for a particular certificate (let's call this the `source`  secret). This prepares the source secret for reflection to possible targets.
In other namespaces you need to create `target` secrets which reflect the `source`.
Reflector will not create the target secrets for you, it will just annotate the source to allow reflection. You have complete control over what and where the target is.

**Comment by sc250024** [comment] 2019-07-04 17:24
@winromulus Thanks for the feedback. So if `cert-manager` is creating a TLS secret in the `cert-manager` namespace, and I want that certificate to be reflected into every other namespace in my cluster, how would I do that?

**Comment by winromulus** [comment] 2019-07-04 17:42
@sc250024 Yes, in the current version, that's the only option.
I'm working on an improved version tonight so I might add something like this. Something like autogenerated targets.
Need to figure out how to annotate the source to define this.
Let me know your thoughts on the following:
- Possible annotations for the source
- How to define each `clone`. Should it have the same name as the source secret? Or a pattern?
- Define which namespaces should be handled.
- Need to consider conflicting targets (existing secret with the same name but different annotations in the other namespaces)
I'm not promising a new version today/tomorrow that can support this but I'm willing to try to figure out a way of doing this and maybe even implement it.

**Comment by sc250024** [comment] 2019-07-05 07:49
@winromulus Thanks for the quick response again! Basically, I think the reflector app is well structured already, I was just surprised it didn't go the step further of creating the secret. Regarding your points:

* I think the source annotations are fine as they are. The `reflector.v1.k8s.emberstack.com/secret-reflection-allowed` annotation for me already implies that it's a source.

* The clone should have the same name. For my case, if it's a TLS certificate, having the cloned secret be the same name gives predictability when I'm creating `Ingress` objects, for example.

* The `reflector.v1.k8s.emberstack.com/secret-reflection-allowed-namespaces` annotation you have is already a great idea. I would make one slight change: if the user wants **all** namespaces, make them use a wildcard like so:

```yaml
reflector.v1.k8s.emberstack.com/secret-reflection-allowed-namespaces: '*'
```

The current behavior is:

> If this annotation is omitted, all namespaces are allowed.

I would make the user opt-in explicitly to say that they want the secret in all namespaces.

* For conflicting targets, Reflector would back off, and not override the secret **unless** it has the `reflector.v1.k8s.emberstack.com/reflects` annotation. The [ExternalDNS](https://github.com/kubernetes-incubator/external-dns) project works in exactly the same way; unless a particular DNS record also has the accompanying TXT record, and the contents exactly match the Service / Ingress, then it doesn't do anything.

> I'm not promising a new version today/tomorrow that can support this but I'm willing to try to figure out a way of doing this and maybe even implement it.

No problem, just happy this project exists at all!

**Comment by winromulus** [comment] 2019-07-10 19:32
@sc250024 - Feature complete and released. It took longer than I expected and the testing was complex, but I got there in the end,
See the updated docs and let me know if you have issues deploying it.
If this helped you, would appreciate a repo star and follow :)

**Comment by sc250024** [comment] 2019-07-11 07:23
Wicked awesome @winromulus , thank you sir! I'll test it out right now.

**Comment by winromulus** [comment] 2019-07-12 11:24
@sc250024 How's the testing going? I have this running in multiple clusters and no hiccups so far

**Comment by winromulus** [comment] 2019-07-12 14:04
Closing issue as the feature has been merged and confirmed as functional. If there are any other issues with it, we'll open a new one.

**Closed by winromulus** 2019-07-12 14:04 UTC
Labels: enhancement

**Comment by sc250024** [comment] 2019-08-08 15:12
@winromulus So sorry, I got caught up. I tried installing the Helm chart (version **2.19197.5**) with the following values:

```yaml
configuration:
  logging:
    minimumLevel: Debug
image:
  tag: release-2.19197.5
  pullPolicy: Always
extensions:
  certManager:
    enabled: true
```

And from the logs of the pod, I get the following logs looping quite fast over each one of my `Certificate` objects:

```plain
cert-reflector-647cc4764d-k2tbp 2019-08-08 15:07:22.362 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Secret watcher Stopping
cert-reflector-647cc4764d-k2tbp 2019-08-08 15:07:22.364 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Secret watcher Stopped
cert-reflector-647cc4764d-k2tbp 2019-08-08 15:07:22.367 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Namespace watcher Stopping
cert-reflector-647cc4764d-k2tbp 2019-08-08 15:07:22.368 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Namespace watcher Stopped
cert-reflector-647cc4764d-k2tbp 2019-08-08 15:07:22.368 +00:00 [INF] (ES.Kubernetes.Reflector.Secrets.Mirror) Restarting watchers
cert-reflector-647cc4764d-k2tbp 2019-08-08 15:07:22.368 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Secret watcher Starting
cert-reflector-647cc4764d-k2tbp 2019-08-08 15:07:22.385 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Secret watcher Started
cert-reflector-647cc4764d-k2tbp 2019-08-08 15:07:22.385 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Namespace watcher Starting
cert-reflector-647cc4764d-k2tbp 2019-08-08 15:07:22.407 +00:00 [DBG] (ES.Kubernetes.Reflector.Secrets.Mirror) V1Namespace watcher Started
cert-reflector-647cc4764d-k2tbp 2019-08-08 15:07:22.607 +00:00 [ERR] (ES.Kubernetes.Reflector.Secrets.Mirror) Failed to process Added Secret cert-manager/star-mycompany-io-ecc-tls due to exception
cert-reflector-647cc4764d-k2tbp System.ArgumentException: parsing '*' - Quantifier {x,y} following nothing.
cert-reflector-647cc4764d-k2tbp    at System.Text.RegularExpressions.RegexParser.ScanRegex()
cert-reflector-647cc4764d-k2tbp    at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
cert-reflector-647cc4764d-k2tbp    at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean addToCache)
cert-reflector-647cc4764d-k2tbp    at System.Text.RegularExpressions.Regex.Match(String input, String pattern)
cert-reflector-647cc4764d-k2tbp    at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
cert-reflector-647cc4764d-k2tbp    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
cert-reflector-647cc4764d-k2tbp    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
cert-reflector-647cc4764d-k2tbp    at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.<>c__DisplayClass16_0.<CheckAutoReflections>b__1(String s) in /src/ES.Kubernetes.Reflector.Core/Mirroring/ResourceMirror.cs:line 248
cert-reflector-647cc4764d-k2tbp    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
cert-reflector-647cc4764d-k2tbp    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
cert-reflector-647cc4764d-k2tbp    at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.CheckAutoReflections(T item)
cert-reflector-647cc4764d-k2tbp    at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.OnResourceWatcherEvent(WatcherEvent`1 request) in /src/ES.Kubernetes.Reflector.Core/Mirroring/ResourceMirror.cs:line 180
cert-reflector-647cc4764d-k2tbp    at ES.Kubernetes.Reflector.Core.Mirroring.ResourceMirror`1.OnEvent(WatcherEvent e) in /src/ES.Kubernetes.Reflector.Core/Mirroring/ResourceMirror.cs:line 96
cert-reflector-647cc4764d-k2tbp    at ES.Kubernetes.Reflector.Core.Queuing.FeederQueue`1.ProcessEventsQueue() in /src/ES.Kubernetes.Reflector.Core/Queuing/FeederQueue.cs:line 52
```

Here's an example of one of my `Certificate` objects:

```yaml
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed-namespaces: "*"
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/secret-reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/secret-reflection-auto-namespaces: "*"
  name: mycompany-io-ecc
  namespace: cert-manager
spec:
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - '*.mycompany.io'
      - mycompany.io
  commonName: '*.mycompany.io'
  dnsNames:
  - mycompany.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  keyAlgorithm: ecdsa
  keyEncoding: pkcs8
  keySize: 384
  secretName: star-mycompany-io-ecc-tls
```

I'm guessing it doesn't like the `*` wildcard?

**Comment by winromulus** [comment] 2019-08-08 15:49
@sc250024 yes. Leave them empty to allow all namespaces. The reason I avoided using "*" is because it is an invalid regex and also it caused backwards compatibility issues. Leave those annotations empty or remove them.

**Comment by sc250024** [comment] 2019-08-09 08:27
@winromulus Got it. I tried it out just now, worked like a charm!

Here's a created secret in the `default` namespace:

```yaml
apiVersion: v1
data:
  ca.crt: ""
  tls.crt: <some-base64-data>
  tls.key: <some-base64-data>
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/auto-reflects: cert-manager/star-my-company-com-ecc-tls
    reflector.v1.k8s.emberstack.com/reflected-at: '"2019-08-09T08:24:41.1794601+00:00"'
    reflector.v1.k8s.emberstack.com/reflected-version: "326732"
    reflector.v1.k8s.emberstack.com/reflects: cert-manager/star-my-company-com-ecc-tls
  creationTimestamp: "2019-08-09T08:24:41Z"
  name: star-my-company-com-ecc-tls
  namespace: default
  resourceVersion: "326756"
  selfLink: /api/v1/namespaces/default/secrets/star-my-company-com-ecc-tls
  uid: 225f7306-ba7f-11e9-a9f9-065d32b2737e
type: kubernetes.io/tls
```

Thank you for your hard work!
